classroom:
  width: 15
  length: 10
  height: 5
  y: 200
  x: 20
  z: 20

day:
  location:
    x: -36
    y: 76
    z: 60
    world: world

quiz:
  sounds:
    correct: ENTITY_PLAYER_LEVELUP
    incorrect: ENTITY_VILLAGER_NO
  particles:
    correct:
      type: HAPPY_VILLAGER
      count: 50
    incorrect:
      type: SMOKE
      count: 30